"""Pydantic response models for the VisualQ Pilot API."""

from typing import Any

from pydantic import BaseModel, Field

from app.models.enums import DifficultyLevel, DiagramType, QuestionSource, QuestionType


class QuestionItem(BaseModel):
    """A single question in a generated paper, either sourced from a PYQ or generated by Gemini."""

    question_id: str
    source: QuestionSource
    type: QuestionType
    marks: int
    chapter: str
    difficulty: DifficultyLevel
    question: str
    options: dict[str, str] = Field(default_factory=dict)
    concept: str | None = None
    requires_diagram: bool = False
    diagram_type: DiagramType = "none"
    diagram_id: str | None = None


class DiagramSpec(BaseModel):
    """A generated diagram specification linked back to its source question."""

    diagram_id: str
    question_id: str
    diagram_type: DiagramType
    specification: dict[str, Any]
    svg: str = ""


class DiagramCoverage(BaseModel):
    """Diagram-coverage analytics for a generated paper."""

    diagram_questions: int = 0
    diagram_percentage: float = 0.0
    free_body: int = 0
    circuit: int = 0
    ray_diagram: int = 0
    graph: int = 0
    magnetic_field: int = 0


class GeneratedPaperResponse(BaseModel):
    """Output payload for POST /api/generate-paper."""

    paper_id: str
    generated_at: str
    difficulty: DifficultyLevel
    total_questions: int
    total_marks: int
    pyq_percentage: int
    ai_percentage: int
    chapter_weightage: dict[str, int]
    chapter_distribution: dict[str, int]
    type_distribution: dict[str, int]
    questions: list[QuestionItem]
    generated_questions: list[QuestionItem]
    diagrams: list[DiagramSpec]
    diagram_coverage: DiagramCoverage


class DetectDiagramResponse(BaseModel):
    """Output payload for POST /api/detect-diagram."""

    requires_diagram: bool
    diagram_type: DiagramType
    confidence: float = Field(ge=0.0, le=1.0)
    reason: str | None = None


class GenerateDiagramResponse(BaseModel):
    """Output payload for POST /api/generate-diagram."""

    diagram_type: DiagramType
    diagram_specification: dict[str, Any]
    svg: str = ""


class HealthResponse(BaseModel):
    """Output payload for GET /api/health."""

    status: str
    service: str
    version: str
    environment: str
    gemini_configured: bool
    datasets: dict[str, int]
