"""Pydantic response models for the VisualQ Pilot API."""

from typing import Any

from pydantic import BaseModel, Field

from app.models.enums import DifficultyLevel, DiagramType, QuestionSource, QuestionType


class QuestionItem(BaseModel):
    """A single question in a generated paper, either sourced from a PYQ or generated by Gemini."""

    question_id: str
    source: QuestionSource
    type: QuestionType
    marks: int
    chapter: str
    difficulty: DifficultyLevel
    question: str
    options: dict[str, str] = Field(default_factory=dict)
    concept: str | None = None
    requires_diagram: bool = False
    diagram_type: DiagramType = "none"
    diagram_id: str | None = None
    question_number: int = 0


class DiagramSpec(BaseModel):
    """A generated diagram specification linked back to its source question."""

    diagram_id: str
    question_id: str
    diagram_type: DiagramType
    specification: dict[str, Any]
    svg: str = ""


class DiagramCoverage(BaseModel):
    """Diagram-coverage analytics for a generated paper."""

    diagram_questions: int = 0
    diagram_percentage: float = 0.0
    free_body: int = 0
    circuit: int = 0
    ray_diagram: int = 0
    graph: int = 0
    magnetic_field: int = 0


class PaperSection(BaseModel):
    """A CBSE-style section (A-E) of a generated paper, with its own questions."""

    name: str
    title: str
    instructions: str
    marks_per_question: int
    question_count: int
    total_marks: int
    questions: list[QuestionItem]


class QualityEvaluation(BaseModel):
    """Automated quality scoring for a generated paper. All fields range 0-100."""

    overall_score: float = 0.0
    cbse_compliance: float = 0.0
    diagram_coverage: float = 0.0
    chapter_coverage: float = 0.0
    difficulty_balance: float = 0.0
    question_diversity: float = 0.0


class GeneratedPaperResponse(BaseModel):
    """Output payload for POST /api/generate-paper."""

    paper_id: str
    generated_at: str
    difficulty: DifficultyLevel
    total_questions: int
    total_marks: int
    pyq_percentage: int
    ai_percentage: int
    chapter_weightage: dict[str, int]
    chapter_distribution: dict[str, int]
    type_distribution: dict[str, int]
    questions: list[QuestionItem]
    generated_questions: list[QuestionItem]
    diagrams: list[DiagramSpec]
    diagram_coverage: DiagramCoverage
    sections: list[PaperSection] = Field(default_factory=list)
    quality_evaluation: QualityEvaluation = Field(default_factory=QualityEvaluation)


class DetectDiagramResponse(BaseModel):
    """Output payload for POST /api/detect-diagram."""

    requires_diagram: bool
    diagram_type: DiagramType
    confidence: float = Field(ge=0.0, le=1.0)
    reason: str | None = None


class GenerateDiagramResponse(BaseModel):
    """Output payload for POST /api/generate-diagram."""

    diagram_type: DiagramType
    diagram_specification: dict[str, Any]
    svg: str = ""


class PhysicsAnalysisModel(BaseModel):
    """Mirrors ``PhysicsAnalysisService.PhysicsAnalysis`` - the ONLY information
    an LLM is allowed to produce about a diagram (no coordinates/geometry)."""

    diagram_required: bool
    diagram_type: DiagramType
    chapter: str | None = None
    concept: str | None = None
    scenario: str | None = None
    entities: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)


class AnalyzeDiagramResponse(BaseModel):
    """Output payload for POST /api/debug/analyze-diagram.

    Exposes every intermediate artifact of the
    Question -> PhysicsAnalyzer -> Template Selection -> SchemaPopulation -> SVG
    pipeline for debugging/inspection.
    """

    question: str
    physics_analysis: PhysicsAnalysisModel
    selected_template: dict[str, Any]
    semantic_schema: dict[str, Any]
    render_schema: dict[str, Any]
    svg: str = ""


class HealthResponse(BaseModel):
    """Output payload for GET /api/health."""

    status: str
    service: str
    version: str
    environment: str
    gemini_configured: bool
    datasets: dict[str, int]
