"""Pydantic response models for the VisualQ Pilot API."""

from typing import Any

from pydantic import BaseModel, Field

from app.models.enums import DifficultyLevel, DiagramType, QuestionSource, QuestionType


class QuestionItem(BaseModel):
    """A single question in a generated paper, either sourced from a PYQ or generated by Gemini."""

    question_id: str
    source: QuestionSource
    type: QuestionType
    marks: int
    chapter: str
    difficulty: DifficultyLevel
    question: str
    options: dict[str, str] = Field(default_factory=dict)
    concept: str | None = None
    requires_diagram: bool = False
    diagram_type: DiagramType = "none"
    diagram_id: str | None = None
    question_number: int = 0


class DiagramSpec(BaseModel):
    """A generated diagram specification linked back to its source question."""

    diagram_id: str
    question_id: str
    diagram_type: DiagramType
    specification: dict[str, Any]
    svg: str = ""
    validation: dict[str, Any] | None = None


class DiagramCoverage(BaseModel):
    """Diagram-coverage analytics for a generated paper."""

    diagram_questions: int = 0
    diagram_percentage: float = 0.0
    free_body: int = 0
    circuit: int = 0
    ray_diagram: int = 0
    graph: int = 0
    magnetic_field: int = 0


class PaperSection(BaseModel):
    """A CBSE-style section (A-E) of a generated paper, with its own questions."""

    name: str
    title: str
    instructions: str
    marks_per_question: int
    question_count: int
    total_marks: int
    questions: list[QuestionItem]


class QualityEvaluation(BaseModel):
    """Automated quality scoring for a generated paper. All fields range 0-100."""

    overall_score: float = 0.0
    cbse_compliance: float = 0.0
    diagram_coverage: float = 0.0
    chapter_coverage: float = 0.0
    difficulty_balance: float = 0.0
    question_diversity: float = 0.0


class GeneratedPaperResponse(BaseModel):
    """Output payload for POST /api/generate-paper."""

    paper_id: str
    generated_at: str
    difficulty: DifficultyLevel
    total_questions: int
    total_marks: int
    pyq_percentage: int
    ai_percentage: int
    chapter_weightage: dict[str, int]
    chapter_distribution: dict[str, int]
    type_distribution: dict[str, int]
    questions: list[QuestionItem]
    generated_questions: list[QuestionItem]
    diagrams: list[DiagramSpec]
    diagram_coverage: DiagramCoverage
    sections: list[PaperSection] = Field(default_factory=list)
    quality_evaluation: QualityEvaluation = Field(default_factory=QualityEvaluation)


class DetectDiagramResponse(BaseModel):
    """Output payload for POST /api/detect-diagram."""

    requires_diagram: bool
    diagram_type: DiagramType
    confidence: float = Field(ge=0.0, le=1.0)
    reason: str | None = None


class DiagramRetrieveAndGenerateResponse(BaseModel):
    """Output payload for POST /api/diagram/retrieve-and-generate."""

    question: str = ""
    classification: dict[str, str] = Field(default_factory=dict)
    retrieved_schema_id: str = ""
    similarity_score: float = 0.0
    diagram_schema: dict[str, Any] = Field(default_factory=dict)
    diagram_url: str = ""


class GenerateDiagramResponse(BaseModel):
    """Output payload for POST /api/generate-diagram."""

    diagram_type: DiagramType
    diagram_specification: dict[str, Any]
    svg: str = ""


class UnderstandingModel(BaseModel):
    """Mirrors ``PhysicsUnderstandingService.UnderstandingLayer`` - the human-readable
    "did the model understand the question" inspection layer."""

    what_is_the_question_asking: str = ""
    what_physics_concept_is_involved: str = ""
    why_is_a_diagram_required: str = ""
    what_must_be_visible: list[str] = Field(default_factory=list)
    what_labels_must_be_present: list[str] = Field(default_factory=list)
    what_examiner_expects_to_see: str = ""


class PhysicsAnalysisModel(BaseModel):
    """Mirrors ``PhysicsUnderstandingService.PhysicsAnalysis`` - the ONLY information
    an LLM is allowed to produce about a diagram (no coordinates/geometry)."""

    diagram_required: bool
    diagram_type: DiagramType
    chapter: str | None = None
    concept: str | None = None
    scenario: str | None = None
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)
    candidate_concepts: list[str] = Field(default_factory=list)
    required_entities: list[str] = Field(default_factory=list)
    relationships: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    labels: list[str] = Field(default_factory=list)
    geometry_rules: dict[str, Any] = Field(default_factory=dict)
    visual_rules: list[str] = Field(default_factory=list)
    validation: list[str] = Field(default_factory=list)
    understanding: UnderstandingModel = Field(default_factory=UnderstandingModel)
    extra: dict[str, Any] = Field(default_factory=dict)
    textbook_context: dict[str, Any] = Field(default_factory=dict)


class NcertContextModel(BaseModel):
    """Mirrors ``PhysicsKnowledgeRetriever.retrieve()`` - the NCERT grounding
    context retrieved for the detected chapter/concept (Phase 2)."""

    chapter: str = ""
    topic: str = ""
    description: str = ""
    diagram_explanation: str = ""
    expected_labels: list[str] = Field(default_factory=list)
    important_points: list[str] = Field(default_factory=list)


class GeneratorSelectionModel(BaseModel):
    """Which specialized physics engine ``DiagramRouter`` selected (Phase 4)."""

    engine: str
    diagram_type: DiagramType
    concept: str | None = None
    scenario: str | None = None


class ValidationReportModel(BaseModel):
    """Mirrors ``DiagramValidationService.validate()`` output (Phase 6)."""

    diagram_score: float = 0.0
    missing_entities: list[str] = Field(default_factory=list)
    missing_labels: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class AnalyzeDiagramResponse(BaseModel):
    """Output payload for POST /api/debug/analyze-diagram.

    Exposes every stage of the
    Question -> Sentence Breakdown -> Physics Understanding -> NCERT Context
    -> Semantic Schema -> Generator Selected -> Generator Input
    -> Validation Report -> Final Diagram pipeline for debugging/inspection.
    """

    question: str
    physics_analysis: PhysicsAnalysisModel
    understanding: UnderstandingModel
    ncert_context: NcertContextModel
    selected_template: dict[str, Any]
    semantic_schema: dict[str, Any]
    generator_selection: GeneratorSelectionModel
    generator_input: dict[str, Any]
    render_schema: dict[str, Any]
    validation_report: ValidationReportModel
    svg: str = ""


class HealthResponse(BaseModel):
    """Output payload for GET /api/health."""

    status: str
    service: str
    version: str
    environment: str
    gemini_configured: bool
    datasets: dict[str, int]
